modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
	modId="customstartinggear"
	displayName="Custom Starter Gear"
    version="2.0.3"
	authors="brandon3055"
	description=''''''

[[dependencies.customstartinggear]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.customstartinggear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
