modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"

[[mods]]
	modId="customstartinggear"
	displayName="Custom Starter Gear"
    version="${version}"
	authors="brandon3055"
	description=''''''

[[dependencies.customstartinggear]]
    modId="forge"
    mandatory=true
    versionRange="[35.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.customstartinggear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
